### ISSUE TITLE
Problema al arrancar (BarHorizontal_32x32.png)

### ISSUE THREAD

**Issue by bifacil** [bifacil/CronoSupport#113]
Un usuario nos informa que le aparece este error al arrancar la versión `24.10.5000` de CronoAnalysis:

![image](https://github.com/crono-bi/CronoSupport/assets/4572969/5da097ce-5814-48ba-aaf0-0776d8a51831)

El texto del error es:

>  (System.Windows.Markup.XamlParseException): No se pudo crear un 'Glyph' a partir del texto 'pack://application:,,,/CronoWpf;component/Resources/img/32x32/BarHorizontal_32x32.png'.

**Comment by bifacil** [comment]
Al tratarse de un usuario concreto sospechámos que se trata de un problema particular de esa instalación. La versión `24.10.5000` está funcionando correctamente en muchos equipos.

Antes de probar otra cosa, trataría de eliminar totalmente esta versión y reinstalarlo...

Crono se instala en esta ubicación:

`C:\Users\[USUARIO]\AppData\Local\CronoAnalysis\app-24.10.5000`

![image](https://github.com/crono-bi/CronoSupport/assets/4572969/c6ab2ebc-960c-4993-b915-24c234139aa7)


Parece un problema similar a este otro, que se solucionó de esta manera:

https://github.com/crono-bi/CronoSupport/issues/109

**Comment by bifacil** [comment]
El usuario nos informa que después de borrar completamente estas carpetas sigue sucediendo;:

C:\Users\XXX\AppData\Local\CronoAnalysis
C:\Users\XXX\AppData\Local\Temp\Crono

![image](https://github.com/crono-bi/CronoSupport/assets/4572969/a8b75b66-7d33-49e4-9244-532b75453c33)

Seguimos investigando...

**Comment by bifacil** [comment]
Esta es la excepción interna...

```
Inner Exception (System.OverflowException): Los datos de la imagen generaron un desbordamiento durante el procesamiento.
   at System.Windows.Media.Imaging.ColorConvertedBitmap.FinalizeCreation()
   at System.Windows.Media.Imaging.ColorConvertedBitmap..ctor(BitmapSource source, ColorContext sourceColorContext, ColorContext destinationColorContext, PixelFormat format)
   at System.Windows.Media.Imaging.BitmapSource.CreateCachedBitmap(BitmapFrame frame, BitmapSourceSafeMILHandle wicSource, BitmapCreateOptions createOptions, BitmapCacheOption cacheOption, BitmapPalette palette)
   at System.Windows.Media.Imaging.BitmapFrameDecode.FinalizeCreation()
   at System.Windows.Media.Imaging.BitmapFrameDecode..ctor(Int32 frameNumber, BitmapCreateOptions createOptions, BitmapCacheOption cacheOption, BitmapDecoder decoder)
   at System.Windows.Media.Imaging.BitmapDecoder.SetupFrames(BitmapDecoder decoder, ReadOnlyCollection`1 frames)
   at System.Windows.Media.Imaging.BitmapDecoder.get_Frames()
   at System.Windows.Media.Imaging.BitmapFrame.CreateFromUriOrStream(Uri baseUri, Uri uri, Stream stream, BitmapCreateOptions createOptions, BitmapCacheOption cacheOption, RequestCachePolicy uriCachePolicy)
   at System.Windows.Media.ImageSourceConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at DevExpress.Xpf.Core.Internal.SvgImageSourceConverter.ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, Object value)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.CreateObjectWithTypeConverter(ServiceProviderContext serviceContext, XamlValueConverter`1 ts, Object value)
   at MS.Internal.Xaml.Runtime.ClrObjectRuntime.CreateFromValue(ServiceProviderContext serviceContext, XamlValueConverter`1 ts, Object value, XamlMember property)
   at MS.Internal.Xaml.Runtime.PartialTrustTolerantRuntime.CreateFromValue(ServiceProviderContext serviceContext, XamlValueConverter`1 ts, Object value, XamlMember property)
   at System.Xaml.XamlObjectWriter.Logic_CreateFromValue(ObjectWriterContext ctx, XamlValueConverter`1 typeConverter, Object value, XamlMember property, String targetName, IAddLineInfo lineInfo)


Inner Exception (System.ArithmeticException): Overflow or underflow in the arithmetic operation.
```

**Comment by bifacil** [comment]
Tal vez sea relevante:

https://stackoverflow.com/questions/63510630/wpf-bitmapimage-exception-the-image-data-generated-an-overflow-during-processin

**Comment by bifacil** [comment]
El usuario nos confirma que es algun problema con el perfil de color. Recientemente ha instalado una pantalla "ultra wide" y le ha puesta esta configuración... ¡que provoca el problema!

![image](https://github.com/crono-bi/CronoSupport/assets/4572969/6fde288d-6fbf-46b6-b564-913a462ecfb2)

En uno de nuestros equipos lo hemos podido reproducir (en otros no).

Puede ser relevante:

https://github.com/fork-dev/TrackerWin/issues/1302
https://www.hanselman.com/blog/dealing-with-images-with-bad-metadata-corrupted-color-profiles-in-wpf

**Comment by bifacil** [comment]
![image](https://github.com/crono-bi/CronoSupport/assets/4572969/0b57ce01-6440-4b71-9c79-d3a55c367075)

**Comment by bifacil** [comment]
Hemos sustitido las imágenes y todo parece funcionar OK.

![image](https://github.com/crono-bi/CronoSupport/assets/4572969/2a4778f1-9ed8-4d71-b8c4-021fd8b4cd89)

El problema era que los metadatos de esas imágenes estaban incorrectos. Las imágenes las habíamos generado nosotros rotando  las barras verticales utizando "Windows Photos", por lo que asumimos que es esta aplicación de Windows quien no rota del todo bien las imágenes. Rotándolo con Photoshop la imagenes tienen los metadatos correctos,.

**Comment by bifacil** [comment]
La versión `24.11.5000` corrige el problema.

**Comment by bifacil** [comment]
Tanquem!
