### ISSUE TITLE
Exportación a Excel

### ISSUE THREAD

**Issue by bifacil** [bifacil/CronoSupport#114]
Nos comunican que desde la versión 24.25 no es posible exportar a Excel un panel:

![image](https://github.com/crono-bi/CronoSupport/assets/4572969/12031530-42ce-4af1-9bef-cf238e32ffad)

```
Crono.Sql.CronoException
------------------------
 (Crono.Sql.CronoException): Ha ocurrido un error imprevisto al exportar la información...

   at Crono.Wpf.Exportacion.CrearDocumentoExportar(FrameworkElement controlToExport, String documentName) in D:\GitHub\CronoETL\src\CronoWpf\Core\Exportacion.vb:line 56
   at Crono.Wpf.Exportacion.Exportar(FrameworkElement ele, ExportTypes ext, String documentName, Boolean openfile) in D:\GitHub\CronoETL\src\CronoWpf\Core\Exportacion.vb:line 129
   at Crono.Analysis.View.BotonExportar.Export(ExportTypes type) in D:\GitHub\CronoETL\src\CronoAnalysis\View\Controles\BotonExportar.xaml.vb:line 61
   at Crono.Analysis.View.BotonExportar._Lambda$__11-6() in D:\GitHub\CronoETL\src\CronoAnalysis\View\Controles\BotonExportar.xaml.vb:line 52
   at Crono.Analysis.View.BotonExportar._Lambda$__R11-10(Object a0)
   at Crono.Wpf.Comando.Execute(Object parameter) in D:\GitHub\CronoETL\src\CronoWpf\Core\RelayCommand.vb:line 131
```

**Comment by bifacil** [comment]
Confirmamos que es un bug introducido en esta versión. La versión 24.15 funcionaba OK. 

Estará corregido en la próxima actualización (mañana a lo más tardar).

**Comment by bifacil** [comment]
El problema está resuelto en la versión `24.25.6000` 

![image](https://github.com/crono-bi/CronoSupport/assets/4572969/6646a0f4-55bd-42ba-bccc-5d79878820a3)
