### ISSUE TITLE
Error al mover columnas 

### ISSUE THREAD

**Issue by bifacil** [bifacil/CronoSupport#115]
Un usuario nos comunica que este error le ha aparecido repetidamente:

![image](https://github.com/user-attachments/assets/bf8ff83e-f304-4555-a0e5-848b5f57ed41)

```
Ha ocurrido un error   en la aplicación y va a cerrarse.
 
Index must be within the bounds of the   List. (Parameter 'index').
 
 
System.ArgumentOutOfRangeException
----------------------------------
(System.ArgumentOutOfRangeException): Index   must be within the bounds of the List. (Parameter 'index')
 
at System.Collections.Generic.List`1.Insert(Int32 index, T item)
at   System.Collections.ObjectModel.ObservableCollection`1.MoveItem(Int32   oldIndex, Int32 newIndex)
at Crono.Common.QueryColumnCollection.MoveItem(Int32 oldIndex, Int32   newIndex)
at System.Collections.ObjectModel.ObservableCollection`1.Move(Int32   oldIndex, Int32 newIndex)
at   Crono.Wpf.Reports.GridViewHelperForQueries.EnsureColumnCorrectIndex(QueryColumnViewModel   col, Int32 newVisibleIndex, HeaderPresenterType moveFrom)
at   Crono.Analysis.AnalysisGridViewHelper.EnsureColumnCorrectIndex(QueryColumnViewModel   col, Int32 newVisibleIndex, HeaderPresenterType moveFrom)
at   Crono.Wpf.Reports.GridViewHelperForQueries.HandleGroupMoveAction(ColumnBase   source, Int32 newVisibleIndex, HeaderPresenterType moveFrom,   HeaderPresenterType moveTo)
at   Crono.Wpf.Reports.TableViewExtendido.HandleGroupMoveAction(ColumnBase source,   Int32 newVisibleIndex, HeaderPresenterType moveFrom, HeaderPresenterType   moveTo, MergeGroupPosition mergeGroupPosition)
at DevExpress.Xpf.Grid.DataViewBase.MoveColumnTo(ColumnBase source,   Int32 newVisibleIndex, HeaderPresenterType moveFrom, HeaderPresenterType   moveTo, MergeGroupPosition mergeGroupPosition)
at   DevExpress.Xpf.Grid.Native.ColumnHeaderDropTargetBase.MoveColumnToGroupMerge(UIElement   source, Int32 dropIndex, MergeGroupPosition mergeGroupPosition)
at   DevExpress.Xpf.Grid.Native.ColumnHeaderDropTargetBase.MoveColumnTo(UIElement   source, Int32 dropIndex)
at   DevExpress.Xpf.Core.Native.HeaderDropTargetBase.MoveColumnToCore(UIElement   source, Object dropAnchor)
at   DevExpress.Xpf.Core.Native.HeaderDropTargetBase.DevExpress.Xpf.Core.IDropTarget.Drop(UIElement   source, Point pt)
at DevExpress.Xpf.Core.Native.DragDropElementHelper.Drop(IDropTarget   dropTarget, Point position)
at   DevExpress.Xpf.Core.Native.DragDropElementHelper.EndDragging(IndependentMouseButtonEventArgs   e)
at   DevExpress.Xpf.Core.Native.DragDropElementHelper.OnMouseLeftButtonUpIndependent(Object   sender, IndependentMouseButtonEventArgs e)
at   DevExpress.Xpf.Core.Native.DragDropElementHelper.OnPreviewMouseLeftButtonUp(Object   sender, MouseButtonEventArgs e)
at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler,   Object target)
at System.Windows.EventRoute.InvokeHandlersImpl(Object source,   RoutedEventArgs args, Boolean reRaised)
at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender,   RoutedEventArgs args, RoutedEvent newEvent)
at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler,   Object target)
at System.Windows.EventRoute.InvokeHandlersImpl(Object source,   RoutedEventArgs args, Boolean reRaised)
at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender,   RoutedEventArgs args)
at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
at System.Windows.Input.InputManager.ProcessStagingArea()
at System.Windows.Input.InputProviderSite.ReportInput(InputReport   inputReport)
at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr   hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x,   Int32 y, Int32 wheel)
at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr   hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd,   Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam,   IntPtr lParam, Boolean& handled)
at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate   callback, Object args, Int32 numArgs)
at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object   source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
 
 
 
SYSTEM INFO
-----------
 
DateTime: 2024-10-18 15:03:30
ReleaseVersion: 24.42
SO: Windows 10 Enterprise (Microsoft   Windows NT 10.0.22631.0)
Framework .Net: 4.8 o superior
```

**Comment by bifacil** [comment]
Investigaremos y lo solucionaremos pronto.

**Comment by bifacil** [comment]
El problema está solucionado.

Estaba relacionado con la existencia de columnas ocultas en las consulta.

Pots provar-ho?

**Comment by bifacil** [comment]
Está solucionado.
